{% set name = "fleximod" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fleximod-{{ version }}.tar.gz
  sha256: 1ccf695f2270325274ccc9a2912f1e995647ab348fbe72ced0e8f2ed73cd481d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gitpython

test:
  imports:
    - fleximod
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jedwards4b/git-fleximod
  summary: Extended support for git-submodule and git-sparse-checkout
  license: MIT
  license_file: License

extra:
  recipe-maintainers:
    - jedwards4b
